# Generated by Django 5.0 on 2023-12-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lneedapp', '0002_remove_userprofile_user_userprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image',
            new_name='profileImage',
        ),
    ]
